In [ ]:
import pandas as pd
import numpy as np


In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()


In [ ]:
data=pd.read_csv("/content/drive/MyDrive/breast-cancer_csv.csv")

In [ ]:
data

age menopause tumor-size inv-nodes node-caps  deg-malig breast  \
0    40-49   premeno      15-19       0-2       yes          3  right   
1    50-59      ge40      15-19       0-2        no          1  right   
2    50-59      ge40      35-39       0-2        no          2   left   
3    40-49   premeno      35-39       0-2       yes          3  right   
4    40-49   premeno      30-34       3-5       yes          2   left   
..     ...       ...        ...       ...       ...        ...    ...   
281  50-59      ge40      30-34       6-8       yes          2   left   
282  50-59   premeno      25-29       3-5       yes          2   left   
283  30-39   premeno      30-34       6-8       yes          2  right   
284  50-59   premeno      15-19       0-2        no          2  right   
285  50-59      ge40      40-44       0-2        no          3   left   

    breast-quad irradiat                 Class  
0       left_up       no     recurrence-events  
1       central       no  no-recurrence-events  
2      left_low       no     recurrence-events  
3      left_low      yes  no-recurrence-events  
4      right_up       no     recurrence-events  
..          ...      ...                   ...  
281    left_low       no  no-recurrence-events  
282    left_low      yes  no-recurrence-events  
283    right_up       no  no-recurrence-events  
284    left_low       no  no-recurrence-events  
285    right_up       no  no-recurrence-events  

[286 rows x 10 columns]

In [ ]:
data['Class']=[1 if each=="recurrence-events" else 0 for each in data.Class]

In [ ]:
data['irradiat']=[0 if each=='no' else 1 for each in data.irradiat]

In [ ]:
data['breast']=[0 if each=='left' else 1 for each in data.breast]

In [ ]:
data['menopause']=[0 if each=='premeno' else 1 for each in data.menopause]

In [ ]:
a=data.drop(['node-caps'],axis=1)

In [ ]:
b=a.drop(['breast-quad'],axis=1)
b

age  menopause tumor-size inv-nodes  deg-malig  breast  irradiat  Class
0    40-49          0      15-19       0-2          3       1         0      1
1    50-59          1      15-19       0-2          1       1         0      0
2    50-59          1      35-39       0-2          2       0         0      1
3    40-49          0      35-39       0-2          3       1         1      0
4    40-49          0      30-34       3-5          2       0         0      1
..     ...        ...        ...       ...        ...     ...       ...    ...
281  50-59          1      30-34       6-8          2       0         0      0
282  50-59          0      25-29       3-5          2       0         1      0
283  30-39          0      30-34       6-8          2       1         0      0
284  50-59          0      15-19       0-2          2       1         0      0
285  50-59          1      40-44       0-2          3       0         0      0

[286 rows x 8 columns]

In [ ]:
b.dtypes

age           object
menopause      int64
tumor-size    object
inv-nodes     object
deg-malig      int64
breast         int64
irradiat       int64
Class          int64
dtype: object

In [ ]:
b['age']= label_encoder.fit_transform(b['age'])
b['tumor-size']=label_encoder.fit_transform(b['tumor-size'])
b['inv-nodes']=label_encoder.fit_transform(b['inv-nodes'])
  


In [ ]:
b

age  menopause  tumor-size  inv-nodes  deg-malig  breast  irradiat  Class
0      2          0           2          0          3       1         0      1
1      3          1           2          0          1       1         0      0
2      3          1           6          0          2       0         0      1
3      2          0           6          0          3       1         1      0
4      2          0           5          4          2       0         0      1
..   ...        ...         ...        ...        ...     ...       ...    ...
281    3          1           5          5          2       0         0      0
282    3          0           4          4          2       0         1      0
283    1          0           5          5          2       1         0      0
284    3          0           2          0          2       1         0      0
285    3          1           7          0          3       0         0      0

[286 rows x 8 columns]

In [ ]:
y=b['irradiat']
x=b.drop(['irradiat'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=100,test_size=0.3)

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
y_pred=dtree.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
y_pred=rf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
z=int(input("age :"))
y=int(input("menopause :"))
x=int(input("tumor-size :"))
w=int(input("inv-nodes :"))
v=int(input("deg-malig :"))
u=int(input("breast :"))

s=int(input("Class :"))

df=pd.DataFrame({"age":[z],
                 "menopause":[y],
                 "tumor-size":[x],
                 "inv-nodes":[w],
                 "deg-malig":[v],
                 "breast":[u],
                 "Class":[s]})
df

age :3
menopause :0
tumor-size :4
inv-nodes :3
deg-malig :7
breast :1
Class :0


age  menopause  tumor-size  inv-nodes  deg-malig  breast  Class
0    3          0           4          3          7       1      0

In [ ]:
y_p=model.predict(df)
y_p

array([0])

In [ ]:
y_pred=dtree.predict(df)
y_pred

array([1])

In [ ]:
y_predict=rf.predict(df)
y_predict

array([0])