In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
houseprice=pd.read_csv("/content/drive/MyDrive/homeprices.csv")

In [ ]:
houseprice

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
y=houseprice['price']
x=houseprice.drop(['price'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=100,test_size=0.3)

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
model.score(x_test,y_test)

0.0

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([550000, 680000])

In [ ]:
area=int(input(" :"))
df=pd.DataFrame({"area":[area]})
df

 :10003


area
0  10003

In [ ]:
y_pred=model.predict(df)
y_pred

array([725000])

In [ ]:
a=int(input(" :"))
df1=pd.DataFrame({"area":[a]})
df1

 :63737


area
0  63737

In [ ]:
y_predict=model.predict(df1)
y_predict

array([725000])

In [ ]:
b=[[3456]]
y_pre=model.predict(b)
y_pre

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([680000])

In [ ]:
c=[[342]]
y=model.predict(c)
y

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([550000])

In [ ]:
d=[[23456]]
y_prediction=model.predict(d)
y_prediction

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([725000])

In [ ]:
e=int(input())
e=[[e]]

y_p=model.predict(e)
y_p

4532


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([725000])

In [ ]:
type(e)

list