In [ ]:
import pandas as pd
import numpy as np


In [ ]:
stroke=pd.read_csv("/content/drive/MyDrive/healthcare-dataset-stroke-data.csv")
stroke

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [ ]:
a=stroke.drop(['id','work_type','Residence_type'],axis=1)

In [ ]:
a

gender   age  hypertension  heart_disease ever_married  \
0       Male  67.0             0              1          Yes   
1     Female  61.0             0              0          Yes   
2       Male  80.0             0              1          Yes   
3     Female  49.0             0              0          Yes   
4     Female  79.0             1              0          Yes   
...      ...   ...           ...            ...          ...   
5105  Female  80.0             1              0          Yes   
5106  Female  81.0             0              0          Yes   
5107  Female  35.0             0              0          Yes   
5108    Male  51.0             0              0          Yes   
5109  Female  44.0             0              0          Yes   

      avg_glucose_level   bmi   smoking_status  stroke  
0                228.69  36.6  formerly smoked       1  
1                202.21   NaN     never smoked       1  
2                105.92  32.5     never smoked       1  
3                171.23  34.4           smokes       1  
4                174.12  24.0     never smoked       1  
...                 ...   ...              ...     ...  
5105              83.75   NaN     never smoked       0  
5106             125.20  40.0     never smoked       0  
5107              82.99  30.6     never smoked       0  
5108             166.29  25.6  formerly smoked       0  
5109              85.28  26.2          Unknown       0  

[5110 rows x 9 columns]

In [ ]:
b=a.fillna(value=22)
b

gender   age  hypertension  heart_disease ever_married  \
0       Male  67.0             0              1          Yes   
1     Female  61.0             0              0          Yes   
2       Male  80.0             0              1          Yes   
3     Female  49.0             0              0          Yes   
4     Female  79.0             1              0          Yes   
...      ...   ...           ...            ...          ...   
5105  Female  80.0             1              0          Yes   
5106  Female  81.0             0              0          Yes   
5107  Female  35.0             0              0          Yes   
5108    Male  51.0             0              0          Yes   
5109  Female  44.0             0              0          Yes   

      avg_glucose_level   bmi   smoking_status  stroke  
0                228.69  36.6  formerly smoked       1  
1                202.21  22.0     never smoked       1  
2                105.92  32.5     never smoked       1  
3                171.23  34.4           smokes       1  
4                174.12  24.0     never smoked       1  
...                 ...   ...              ...     ...  
5105              83.75  22.0     never smoked       0  
5106             125.20  40.0     never smoked       0  
5107              82.99  30.6     never smoked       0  
5108             166.29  25.6  formerly smoked       0  
5109              85.28  26.2          Unknown       0  

[5110 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()


In [ ]:
b['gender']=label_encoder.fit_transform(b['gender'])
b['ever_married']=label_encoder.fit_transform(b['ever_married'])
b["smoking_status"]=label_encoder.fit_transform(b['smoking_status'])

In [ ]:
b

gender   age  hypertension  heart_disease  ever_married  \
0          1  67.0             0              1             1   
1          0  61.0             0              0             1   
2          1  80.0             0              1             1   
3          0  49.0             0              0             1   
4          0  79.0             1              0             1   
...      ...   ...           ...            ...           ...   
5105       0  80.0             1              0             1   
5106       0  81.0             0              0             1   
5107       0  35.0             0              0             1   
5108       1  51.0             0              0             1   
5109       0  44.0             0              0             1   

      avg_glucose_level   bmi  smoking_status  stroke  
0                228.69  36.6               1       1  
1                202.21  22.0               2       1  
2                105.92  32.5               2       1  
3                171.23  34.4               3       1  
4                174.12  24.0               2       1  
...                 ...   ...             ...     ...  
5105              83.75  22.0               2       0  
5106             125.20  40.0               2       0  
5107              82.99  30.6               2       0  
5108             166.29  25.6               1       0  
5109              85.28  26.2               0       0  

[5110 rows x 9 columns]

In [ ]:
y=b['stroke']
x=b.drop(['stroke'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=100,test_size=0.3)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
x_test

gender   age  hypertension  heart_disease  ever_married  \
2918       0  63.0             0              1             1   
3056       1  62.0             0              1             1   
4916       1  54.0             0              0             1   
4003       0  24.0             0              0             0   
3332       1  27.0             0              0             1   
...      ...   ...           ...            ...           ...   
3238       0  57.0             0              0             1   
3716       0  69.0             0              0             0   
3862       0  54.0             0              0             1   
3941       0  32.0             0              0             1   
4630       1  31.0             0              0             1   

      avg_glucose_level   bmi  smoking_status  
2918             239.95  32.2               3  
3056              73.70  26.2               2  
4916              72.96  37.7               3  
4003             147.74  21.4               0  
3332             114.32  28.1               0  
...                 ...   ...             ...  
3238             176.78  50.4               2  
3716              59.31  31.4               3  
3862              68.60  44.8               3  
3941              67.10  27.1               0  
4630              79.81  26.4               2  

[1533 rows x 8 columns]

In [ ]:
y_predict=knn.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_predict=dtree.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_predict=rf.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
a=int(input("gender :"))
b=int(input("age :"))
c=int(input("hypertension :"))
d=int(input("hear_disease :"))
e=int(input("ever_married :"))
f=float(input("avg_glucose_level :"))
g=float(input("bmi :"))
h=int(input("smokin_status :"))
df=pd.DataFrame({"gender":[a],
                 "age":[b],
                 "hypertension":[c],
                 "hear_disease":[d],
                 "ever_married":[e],
                 "avg_glucose_level":[f],
                 "bmi":[g],
                 "smokin_status":[h]})
df

gender :1
age :34
hypertension :3
hear_disease :5
ever_married :4
avg_glucose_level :2.4
bmi :34.6
smokin_status :2


gender  age  hypertension  hear_disease  ever_married  avg_glucose_level  \
0       1   34             3             5             4                2.4   

    bmi  smokin_status  
0  34.6              2

In [ ]:
y_predict=knn.predict(df)
y_predict

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- hear_disease
- smokin_status
Feature names seen at fit time, yet now missing:
- heart_disease
- smoking_status

  warnings.warn(message, FutureWarning)


array([0])

In [ ]:
y_predict=dtree.predict(df)
y_predict

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- hear_disease
- smokin_status
Feature names seen at fit time, yet now missing:
- heart_disease
- smoking_status

  warnings.warn(message, FutureWarning)


array([0])

In [ ]:
y_pr=rf.predict(df)
y_pr

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- hear_disease
- smokin_status
Feature names seen at fit time, yet now missing:
- heart_disease
- smoking_status

  warnings.warn(message, FutureWarning)


array([0])

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
y_p=model.predict(df)
y_p

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- hear_disease
- smokin_status
Feature names seen at fit time, yet now missing:
- heart_disease
- smoking_status

  warnings.warn(message, FutureWarning)


array([0])