In [ ]:
import pandas as pd
import numpy as np


In [ ]:
weather=pd.read_csv("/content/drive/MyDrive/seattle-weather.csv")
weather

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [ ]:
a=weather.drop(['date'],axis=1)

In [ ]:
a

precipitation  temp_max  temp_min  wind  weather
0               0.0      12.8       5.0   4.7  drizzle
1              10.9      10.6       2.8   4.5     rain
2               0.8      11.7       7.2   2.3     rain
3              20.3      12.2       5.6   4.7     rain
4               1.3       8.9       2.8   6.1     rain
...             ...       ...       ...   ...      ...
1456            8.6       4.4       1.7   2.9     rain
1457            1.5       5.0       1.7   1.3     rain
1458            0.0       7.2       0.6   2.6      fog
1459            0.0       5.6      -1.0   3.4      sun
1460            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]

In [ ]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [ ]:
a['weather']=label_encoder.fit_transform(a['weather'])

In [ ]:
a

precipitation  temp_max  temp_min  wind  weather
0               0.0      12.8       5.0   4.7        0
1              10.9      10.6       2.8   4.5        2
2               0.8      11.7       7.2   2.3        2
3              20.3      12.2       5.6   4.7        2
4               1.3       8.9       2.8   6.1        2
...             ...       ...       ...   ...      ...
1456            8.6       4.4       1.7   2.9        2
1457            1.5       5.0       1.7   1.3        2
1458            0.0       7.2       0.6   2.6        1
1459            0.0       5.6      -1.0   3.4        4
1460            0.0       5.6      -2.1   3.5        4

[1461 rows x 5 columns]

In [ ]:
y=a['weather']
x=a.drop(['weather'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=100,test_size=0.3)

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_predict=model.predict(x_test)
y_test

1437    2
57      4
780     2
382     0
1170    2
       ..
555     4
399     2
545     4
266     1
210     4
Name: weather, Length: 439, dtype: int64

In [ ]:
y_predict=rf.predict(x_test)
y_predict

array([2, 4, 2, 4, 2, 2, 4, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 1, 4, 4, 4,
       4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 2, 4, 2, 4, 4, 4, 2, 2, 2, 4, 4, 2,
       2, 4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 4,
       4, 4, 4, 1, 2, 4, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 4, 3, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 1, 2, 4, 4, 2, 2, 1,
       2, 2, 4, 2, 3, 4, 0, 4, 4, 4, 4, 4, 2, 2, 4, 4, 4, 1, 4, 4, 4, 2,
       2, 2, 2, 4, 1, 4, 4, 4, 2, 4, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 4, 4,
       2, 4, 0, 4, 4, 4, 2, 2, 2, 4, 2, 4, 4, 1, 4, 2, 2, 4, 2, 2, 2, 2,
       4, 2, 4, 2, 4, 4, 2, 3, 2, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 4, 2, 2,
       2, 1, 2, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 4, 4, 1, 4, 4, 2, 1, 4, 2, 4,
       2, 1, 4, 4, 4, 4, 2, 4, 1, 4, 4, 2, 4, 2, 1, 2, 4, 4, 2, 2, 2, 4,
       4, 1, 4, 2, 2, 2, 4, 1, 2, 2, 2, 4, 4, 2, 1, 2, 4, 4, 4, 2, 1, 4,
       2, 4, 2, 4, 4, 4, 4, 4, 2, 4, 1, 2, 4, 4, 4,

In [ ]:
y=dtree.predict(x_test)
y

array([2, 4, 2, 4, 2, 2, 0, 4, 2, 2, 1, 4, 4, 4, 2, 2, 2, 2, 1, 4, 4, 4,
       4, 2, 2, 2, 4, 2, 1, 4, 2, 4, 2, 4, 2, 4, 4, 4, 2, 2, 2, 4, 1, 2,
       2, 4, 2, 4, 4, 2, 2, 1, 1, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 4,
       4, 2, 4, 1, 2, 4, 2, 4, 2, 2, 0, 4, 2, 2, 2, 2, 4, 4, 3, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 0,
       2, 2, 4, 2, 3, 4, 0, 4, 2, 4, 4, 4, 2, 3, 4, 4, 0, 1, 4, 2, 4, 2,
       2, 2, 2, 4, 4, 4, 0, 4, 2, 4, 4, 2, 3, 2, 4, 2, 2, 2, 1, 4, 2, 4,
       2, 4, 0, 4, 4, 4, 2, 2, 2, 4, 2, 4, 1, 1, 4, 2, 2, 1, 2, 2, 2, 2,
       4, 2, 4, 2, 4, 0, 2, 3, 2, 2, 2, 2, 2, 0, 1, 1, 0, 2, 2, 1, 2, 2,
       2, 1, 3, 2, 2, 2, 4, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 4, 4, 1, 1, 4, 2, 1, 2, 2, 1,
       2, 1, 0, 4, 1, 1, 2, 4, 1, 4, 4, 2, 1, 2, 1, 2, 4, 4, 2, 2, 2, 4,
       4, 1, 4, 2, 2, 2, 4, 1, 2, 2, 2, 4, 4, 2, 1, 2, 4, 4, 4, 2, 1, 4,
       2, 0, 2, 4, 1, 4, 4, 4, 2, 1, 1, 2, 4, 4, 4,

In [ ]:
a=int(input("precipitation :"))
b=int(input("temp_max :"))
c=int(input("temp_min :"))
d=int(input("wind :"))
df=pd.DataFrame({"precipitation":[a],
                 "temp_max":[b],
                 "temp_min":[c],
                 "wind":[d]})
df

precipitation :8
temp_max :12
temp_min :4
wind :5


precipitation  temp_max  temp_min  wind
0              8        12         4     5

In [ ]:
y_p=model.predict(df)
y_p

array([2])

In [ ]:
y_pr=dtree.predict(df)
y_pr

array([2])

array([2])

In [ ]:
y_pred=rf.predict(df)
y_pred

array([2])