In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
winequality=pd.read_csv("/content/drive/MyDrive/winequality.csv")
winequality

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [ ]:
y=winequality['quality']
x=winequality.drop(['quality'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=100,test_size=0.3)

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5,
       5, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 5, 5,
       5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6,
       6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6,
       6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 6, 6, 5,
       5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6,
       6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6,
       5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6,
       5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 5,

In [ ]:
a=int(input("fixed acidity :"))
b=int(input("volatile acidity :"))
c=int(input("citric acid :"))
d=int(input("residual sugar :"))
e=int(input("chlorides :"))
f=int(input("free sulfur dioxide :"))
g=int(input("total sulfur dioxide :"))
h=int(input("density :"))
i=int(input('pH	:'))
j=int(input("sulpahtes :"))
k=int(input('alcohol :'))
df=pd.DataFrame({"fixed acidity":[a],
                 "volatile acidity":[b],
                 "citric acid":[c],
                 "residual sugar":[d],
                 "chlorides":[e],
                 "free sulfur dioxide":[f],
                 "total sulfur dioxide":[g],
                 "dencity":[h],
                 "pH":[i],
                 "sulphates":[j],
                 "alcohol":[k]})
df

fixed acidity :3
volatile acidity :45
citric acid :23
residual sugar :78
chlorides :3
free sulfur dioxide :8
total sulfur dioxide :9
density :34
pH	:6
sulpahtes :6
alcohol :45


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              3                45           23              78          3   

   free sulfur dioxide  total sulfur dioxide  dencity  pH  sulphates  alcohol  
0                    8                     9       34   6          6       45

In [ ]:
y_pred=model.predict(df)
y_pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- dencity
Feature names seen at fit time, yet now missing:
- density

  warnings.warn(message, FutureWarning)


array([6])

In [ ]:
a=int(input("fixed acidity :"))
b=int(input("volatile acidity :"))
c=int(input("citric acid :"))
d=int(input("residual sugar :"))
e=int(input("chlorides :"))
f=int(input("free sulfur dioxide :"))
g=int(input("total sulfur dioxide :"))
h=int(input("density :"))
i=int(input('pH	:'))
j=int(input("sulpahtes :"))
k=int(input('alcohol :'))
df1=pd.DataFrame({"fixed acidity":[a],
                 "volatile acidity":[b],
                 "citric acid":[c],
                 "residual sugar":[d],
                 "chlorides":[e],
                 "free sulfur dioxide":[f],
                 "total sulfur dioxide":[g],
                 "dencity":[h],
                 "pH":[i],
                 "sulphates":[j],
                 "alcohol":[k]})
df1


fixed acidity :3
volatile acidity :56
citric acid :34
residual sugar :3
chlorides :4
free sulfur dioxide :8
total sulfur dioxide :7
density :4
pH	:3
sulpahtes :4
alcohol :3


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              3                56           34               3          4   

   free sulfur dioxide  total sulfur dioxide  dencity  pH  sulphates  alcohol  
0                    8                     7        4   3          4        3

In [ ]:
y_predict=model.predict(df1)
y_predict

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- dencity
Feature names seen at fit time, yet now missing:
- density

  warnings.warn(message, FutureWarning)


array([5])